# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 269b802f071fe2879d531ba56d7163042df3039e8442c18f59512e1babfd6725edcaaae882173c0ca95c27fb55fa0dfabab533dc561ce23e7b65abd693323b1d

test:
  secret_key_base: e7341544587751816a30c5694ed76ab5f6fe99604d4699b429f56274b9bb6204abf0d23e4f0445a566eed86fd4cc1238099da0210eb6d39a655a10df6a1d529e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
